version: "3.8"
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app/backend
    expose:
      - "3000"
    networks:
      - appnet

  php:
    image: php:8.1-fpm
    volumes:
      - ./public:/var/www/html
      - ./public/messages.db:/var/www/html/messages.db
    networks:
      - appnet

  nginx:
    image: nginx:alpine
    ports:
      - "80"
    volumes:
      - ./public:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - appnet

networks:
  appnet:
