version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatsapp-node
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app/backend
      - ./public:/app/public
    working_dir: /app/backend
